mysite/accmanage/urls.py
from django.urls import path
from . import views


app_name = 'accmanage'

urlpatterns = [
    path('', views.index, name='index'),
    path('acc/delete/<int:acc_id>/', views.acc_delete, name='acc_delete'),
]

mysite/common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('signup/', views.signup, name='signup'),
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import include, path

from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

mysite/pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

mysite/swesite/urls.py
from django.contrib import admin
from django.urls import path, include
from accmanage import views

urlpatterns = [
    path('accmanage/', include('accmanage.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('common/', include('common.urls'))
]

mysite/accmanage/models.py
from django.db import models

mysite/common/models.py
# from django.db import models
#
#
# class Account(models.Model):
#     username = models.CharField(max_length=200)
#     password1 = models.TextField(max_length=200)
#     password2 = models.TextField(max_length=200)
#     job = models.TextField(max_length=200)

# from django.db import models
# from django.contrib.auth.models import User
# from django.db.models.signals import post_save
# from django.dispatch import receiver
#
# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     job = models.CharField(max_length=10, blank=True)
#
# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

mysite/pybo/models.py
from django.db import models


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

mysite/accmanage/forms.py
from django import forms
from accmanage.models import Accinfo

mysite/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    first_name = forms.CharField(label="직업")

    class Meta:
        model = User
        fields = ("username", "first_name")

mysite/pybo/forms.py
from django import forms

from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

mysite/accmanage/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.shortcuts import render
from common.forms import UserForm
from django.contrib.auth.models import User


def index(request):
    acc_list = User.objects.order_by('id')
    context = {'acc_list': acc_list}

    return render(request, 'accmanage/acc_list.html', context)


def acc_delete(request, acc_id):
    acc = User.objects.get(id=acc_id)
    acc.delete()
    return redirect('accmanage:index')

mysite/common/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            acc = form.save(commit=False)
            acc.save()
            # username = form.cleaned_data.get('username')
            # raw_password = form.cleaned_data.get('password1')
            # user = authenticate(username=username, password=raw_password)
            # login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})
# Create your views here.

mysite/pybo/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import QuestionForm, AnswerForm
from .models import Question


def index(request):
    """
    pybo 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지

    # 조회
    question_list = Question.objects.order_by('-create_date')

    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """
    pybo 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


def question_create(request):
    """
    pybo 질문등록
    """
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

mysite/templates/accmanage/acc_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>이름</th>
            <th>직업</th>
            <th>삭제</th>
        </tr>
        </thead>
        <tbody>
        {% if acc_list %}
        {% for acc in acc_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ acc.username }}</td>
            <td>{{ acc.first_name }}</td>
            <td>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                data-uri="{% url 'accmanage:acc_delete' acc.id  %}">삭제</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">계정이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <title>Hello, pybo!</title>
</head>
<body>
{% include "navbar.html" %}
{% block content %}
{% endblock %}
{% block script %}
{% endblock %}
</body>
</html>

mysite/templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

mysite/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="first_name">직업</label>
            <input type="text" class="form-control" name="first_name" id="first_name"
                   value="{{ form.job.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

mysite/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

mysite/templates/navbar.html
{#<!-- 네비게이션바 -->#}
{#<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">#}
{#    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>#}
{#    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"#}
{#        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">#}
{#        <span class="navbar-toggler-icon"></span>#}
{#    </button>#}
{#    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">#}
{#        <ul class="navbar-nav">#}
{#            <li class="nav-item ">#}
{#                {% if user.is_authenticated %}#}
{#                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>#}
{#                {% else %}#}
{#                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>#}
{#                {% endif %}#}
{#            </li>#}
{#        </ul>#}
{#    </div>#}
{#</nav>#}

mysite/templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}